pipeline {
    agent none
    stages {
        
        stage("Unit Tests") {
            agent {
            docker { image 'ubuntu:latest' }
        }
            steps {
                sh 'apt update'
                sh 'apt install node npm -y'
                git url: 'https://github.com/himavanthreddy94/tictactoe-devsecops-pipeline.git', branch: 'main'
                sh 'npm ci'
                sh 'npm test'
            }
        }
        stage("Lint") {
            agent {
            docker { image 'ubuntu:latest' }
        }
            steps {
                sh 'apt update'
                sh 'apt install node npm -y'
                git url: 'https://github.com/himavanthreddy94/tictactoe-devsecops-pipeline.git', branch: 'main'
                sh 'npm ci'
                sh 'npm run lint'
            }
        }
        stage("Build") {
            agent {
            docker { image 'ubuntu:latest' }
        }
            steps {
                sh 'apt update'
                sh 'apt install node npm -y'
                git url: 'https://github.com/himavanthreddy94/tictactoe-devsecops-pipeline.git', branch: 'main'
                sh 'npm ci'
                sh 'npm run build'
                archiveArtifacts artifacts: 'dist/**', followSymlinks: false
            }
        }

    }
}

