pipeline {
    agent none
    stages {
        stage("Unit Tests") {
            agent {
                docker { image 'node:20-alpine' }
            }
            steps {
                git url: 'https://github.com/OWNER/REPO.git', branch: 'main'
                sh 'npm install'
                sh 'npm test'
            }
        }
        stage("Lint") {
            agent {
                docker { image 'node:20-alpine' }
            }
            steps {
                git url: 'https://github.com/OWNER/REPO.git', branch: 'main'
                sh 'npm install'
                sh 'npm run lint'
            }
        }
        stage("Build") {
            agent {
                docker { image 'node:20-alpine' }
            }
            steps {
                'git url: 'https://github.com/OWNER/REPO.git', branch: 'main'   
                sh 'npm install'
                sh 'npm run build'
                archiveArtifacts artifacts: '/dist', followSymlinks: false
            }
        }

    }
}